all:
  children:

    webservers:
      hosts:
        web01:
          ansible_host: 127.0.0.1
          ansible_port: 2221

        web02:
          ansible_host: 127.0.0.1
          ansible_port: 2222

    databases:
      hosts:
        db01:
          ansible_host: 127.0.0.1
          ansible_port: 2223

  vars:
    ansible_user: ansible
