all:
  children:

    webservers:
      hosts:
        web01:
          ansible_host: 127.0.0.1
          ansible_port: 2221
      vars:
        php_package: libapache2-mod-php

    databases:
      hosts:
        db01:
          ansible_host: 127.0.0.1
          ansible_port: 2223

    workload:
      hosts:
        wkl01:
          ansible_host: 127.0.0.1
          ansible_port: 2222

  vars:
    ansible_user: ansible
    apache_package: apache2
