---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_os_family in ["Debian", "Ubuntu"]

- hosts: workload
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip
      state: latest

  - name: Install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: webservers
  become: true
  tasks:

  - name: Install apache and PHP for Ubuntu servers
    tags: ubuntu,apache,apache2,php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_os_family in ["Debian", "Ubuntu"]

  - name: Install apache and PHP for CentOS Servers
    tags: centos,apache,apache2,php
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_os_family == "CentOS"

  - name: Copy default page
    tags: apache,apache2,httpd
    copy:
      src: ../files/index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Change default page content
    tags: apache,apache2
    lineinfile:
      path: /var/www/html/index.html
      regexp: '^<h1>This is a test'
      line: "Almost there"

  - name: Restart service to apply changes
    tags: apache,apache2
    service:
      name: apache2
      state: restarted


- hosts: databases
  become: true
  tasks:

  - name: Install mariaDB in Ubuntu server
    tags: ubuntu, mariadb,db
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_os_family in ["Debian", "Ubuntu"]

  - name: Install mariaDB in CentOS Server
    tags: centos,db,mariadb
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_os_family == "CentOS"
