---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package and PHP and update
    apt:
      name: 
        - apache2
        - php
      update_cache: yes
      state: latest
   #  when: ansible_distribution in ["Ubuntu", "Debian"] 

